#include "aboutpage.h"
#include <QDebug>
#include <QFontDatabase>
namespace PTG {
    namespace view {
        AboutPage::AboutPage(QWidget * parent) : Page(parent),
            description(new QLabel),
            title(new QLabel),
            button(new QPushButton)
        {
            qDebug() << "AboutPage()\n";

            description->setText("This is a 2D tile-based procedural terrain generator. The terrain"
                             "will be generated by a heightmap of random noise and basic heat, wind, climate, and biome"
                             "models. Terrain will be visualized as 2D pixel-art.");
            description->setWordWrap(true);
            title->setText("About");
            title->setAlignment(Qt::AlignCenter);
            button->setText("Back");

            addPageWidget(title);
            addPageWidget(description);
            addPageWidget(button);

            setPageLayout();

            QObject::connect(button,SIGNAL(clicked()),this,SLOT(buttonPushed()));

            setPageStyle();
        }
        AboutPage::~AboutPage() {

        }
        void AboutPage::buttonPushed() {
            qDebug() << "about page button pushed\n";
            emit Page::setPage(0);
        }
        void AboutPage::setPageStyle() {
            this->setStyleSheet("border: 5px solid white;"
                              "color: white;"
                              "font: 'Times New Roman';"
                              "font-size: 42px;"
                              "border-radius: 4px;"
                              "padding: 5px;"
                              "text-align: center;"
                              "background-color: rgba(40,25,20, .6);");
            title->setStyleSheet("color: white;"
                              "font-size: 111px;"
                              "font-variant: small-caps;"
                              "font-weight: bold;"
                              "border-radius: 5px;"
                              "padding: 2px;"
                              "text-align: center;");
            button->setStyleSheet("font-size: 50px;"
                                  "font-variant: small-caps;"
                                  "font-weight: bold;"
                                  "background-color: rgba(40,25,20, .6);"
                                  "text-align: center;");

            if(QFontDatabase::addApplicationFont(":/font/monogram.ttf"))
                qDebug("font loaded");
            QFont monogram("monogram");
            title->setFont(monogram);
            description->setFont(monogram);
            button->setFont(monogram);
        }
    }
}
