#include "aboutpage.h"
#include <QDebug>
#include <QFontDatabase>
#include "view/ptgbutton.h"

namespace PTG {
    namespace view {
        AboutPage::AboutPage(QWidget * parent) : Page(parent),
            description(new QLabel),
            title(new QLabel),
            backButton(new PTGButton)
        {
            qDebug() << "AboutPage()";

            // add description text
            description->setText("This is a 2D tile-based procedural terrain generator. The terrain "
                             "will be generated by a heightmap of random noise and from a basic climate model. "
                             "Terrain will be visualized as colored tiles on a 2D grid.  Special thanks to:"
                             "\n* Vinicius \"datagoblin\" Menezio for the Monogram font.  "
                             "Monogram is under a creative common license."
                             "\n* Martin Afford for an implementation of the diamond square algorithm.  "
                             "Their implementation is under MIT Licence."
                             "\n* Ryo \"Reputeless\" Suzuki for an implementation of Perlin Noise.  "
                             "Their implementation includes permission to reuse.");
            description->setWordWrap(true); // enable word wrap
            title->setText("About");  // set the label text
            title->setAlignment(Qt::AlignCenter); // make sure it's cenetered
            backButton->setText("Back"); // set button text

            addPageWidget(title); // add title first
            addPageWidget(description); // then add description label
            addPageWidget(backButton); // lastly add the button

            setPageLayout(); // set the (page) layout of widget

            // when back button is clicked, call the back Button pushed
            QObject::connect(backButton,SIGNAL(clicked()),this,SLOT(backButtonPushed()));

            setPageStyle();
        }
        AboutPage::~AboutPage() {

        }
        void AboutPage::backButtonPushed() {
            qDebug() << "about page backButton pushed";
            emit Page::setPage(0); // send a signal corresponding the welcome page
        }
        void AboutPage::setPageStyle() {
            Page::setPageStyle(); // setting the default page style, but there is more to add
            title->setStyleSheet("color: white;"
                              "font-size: 90px;"
                              "font-variant: small-caps;"
                              "font-weight: bold;"
                              "border-radius: 5px;"
                              "padding: 2px;"
                              "text-align: center;");

            if(QFontDatabase::addApplicationFont(":/font/monogram.ttf"))
                qDebug("font loaded");
            // give everything the monogram font.
            QFont monogram("monogram");
            title->setFont(monogram);
            description->setFont(monogram);
            backButton->setFont(monogram);
        }
    }
}
