#include "firstpage.h"
#include <QDebug>
#include <QFontDatabase>
namespace PTG {
    namespace view {
        FirstPage::FirstPage(QWidget *parent) : Page(parent),
            message(new QLabel),
            title(new QLabel),
            button(new QPushButton)
          {
            qDebug() << "FirstPage()\n";

            message->setText("This is a 2D tile-based procedural terrain generator. The terrain"
                             "will be generated by a heightmap of random noise and basic heat, wind, climate, and biome"
                             "models. Terrain will be visualized as 2D pixel-art.");
            message->setWordWrap(true);
            title->setText("Procedural Terrain Generator");
            title->setAlignment(Qt::AlignCenter);
            button->setText("Start");

            qDebug() << "widgets set\n";
            addPageWidget(title);
            addPageWidget(message);
            addPageWidget(button);

            setPageLayout();

            //QObject::connect(button,SIGNAL(clicked()),this,SLOT(buttonPushed()));

            setPageStyle();
            qDebug() << "end of FirstPage()\n";
        }

        void FirstPage::buttonPushed(){
            qDebug() << "first page button pushed\n";
            //emit Page::setPage(1);
        }

        void FirstPage::setPageStyle(){
            Page::setPageStyle();
            title->setStyleSheet("color: white;"
                              "font-size: 111px;"
                              "font-variant: small-caps;"
                              "font-weight: bold;"
                              "border-radius: 5px;"
                              "padding: 2px;"
                              "text-align: center;");
            button->setStyleSheet("font-size: 50px;"
                                  "font-variant: small-caps;"
                                  "font-weight: bold;"
                                  "background-color: rgba(40,25,20, .6);"
                                  "text-align: center;");

            if(QFontDatabase::addApplicationFont(":/font/monogram.ttf"))
                qDebug("font loaded");
            QFont monogram("monogram");
            title->setFont(monogram);
            message->setFont(monogram);
            button->setFont(monogram);
        }
    }
}
